from typing import Protocol, List, Dict, Optional, Any, runtime_checkable

@runtime_checkable
class Element(Protocol):
    @property
    def tag_name(self) -> str: ...
    @property
    def classes(self) -> List[str]: ...
    @property
    def id_attr(self) -> Optional[str]: ...
    @property
    def text(self) -> str: ...
    @property
    def xpath(self) -> str: ...
    @property
    def rect(self) -> Optional[Dict[str, float]]: ...
    def get_attribute(self, name: str) -> Optional[str]: ...

@runtime_checkable
class Adapter(Protocol):
    def query(self, ctx: Any, selector: str) -> Optional[Any]: ...
    def query_all(self, ctx: Any, selector: str) -> List[Any]: ...
    def query_candidates(self, ctx: Any, tag_name: str) -> List[Any]: ...
    def extract_features(self, el: Any, ctx: Optional[Any] = None) -> Dict[str, Any]: ...
    def extract_features_bulk(self, ctx: Any, candidates: List[Any]) -> List[Dict[str, Any]]: ...
